node('master')
{
    stage('ContinuousDownload') 
    {
         https://github.com/rakeshguptha/nagesh.git
    }
    stage('ContinuousBuild') 
    {
         sh label: '', script: 'mvn package'
    }
    stage('ContinuousDeployment')
    {
        sh label: '', script: 'scp /home/ubuntu/.jenkins/workspace/ScriptedPipeline/webapp/target/webapp.war ubuntu@172.31.19.245:/var/lib/tomcat8/webapps/testenv.war'
    }
    
    
}

